local Vec = require("src.lovevec")
local assert = require("luassert")

describe("Arithmetics", function()
  before_each(function()
    Vec.enable_debug(true)
  end)

  after_each(function()
    Vec.enable_debug(false)
  end)

  describe("add", function()
    it("should add two Vecs", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(3, 4)
      local result = v1:add(v2)
      assert.are.same(result, Vec(4, 6))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):add("a")
      end, "bad argument #1 to 'add' (Vec expected, got string)")
    end)
  end)

  describe("add_", function()
    it("should add a Vec in-place", function()
      local v = Vec(1, 2)
      v:add_(Vec(3, 4))
      assert.are.same(v, Vec(4, 6))
    end)
    it("should error if the argument is not a Vec", function()
      local v = Vec(1, 2)
      assert.has_error(function()
        v:add_("a")
      end, "bad argument #1 to 'add_' (Vec expected, got string)")
    end)
  end)

  describe("sub", function()
    it("should subtract two Vecs", function()
      local v1 = Vec(5, 6)
      local v2 = Vec(3, 4)
      local result = v1:sub(v2)
      assert.are.same(result, Vec(2, 2))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(5, 6):sub("a")
      end, "bad argument #1 to 'sub' (Vec expected, got string)")
    end)
  end)

  describe("sub_", function()
    it("should subtract a Vec in-place", function()
      local v = Vec(5, 6)
      v:sub_(Vec(3, 4))
      assert.are.same(v, Vec(2, 2))
    end)
    it("should error if the argument is not a Vec", function()
      local v = Vec(5, 6)
      assert.has_error(function()
        v:sub_("a")
      end, "bad argument #1 to 'sub_' (Vec expected, got string)")
    end)
  end)

  describe("mul", function()
    it("should multiply a Vec by a scalar", function()
      local v = Vec(2, 3)
      local result = v:mul(2)
      assert.are.same(result, Vec(4, 6))
    end)
    it("should error if the argument is not a number", function()
      assert.has_error(function()
        Vec(2, 3):mul("a")
      end, "bad argument #1 to 'mul' (finite number expected, got a)")
    end)
  end)

  describe("mul_", function()
    it("should multiply a Vec in-place by a scalar", function()
      local v = Vec(2, 3)
      v:mul_(2)
      assert.are.same(v, Vec(4, 6))
    end)
    it("should error if the argument is not a number", function()
      local v = Vec(2, 3)
      assert.has_error(function()
        v:mul_("a")
      end, "bad argument #1 to 'mul_' (finite number expected, got a)")
    end)
  end)

  describe("mulv", function()
    it("should multiply two Vecs element-wise", function()
      local v1 = Vec(2, 3)
      local v2 = Vec(4, 5)
      local result = v1:mulv(v2)
      assert.are.same(result, Vec(8, 15))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(2, 3):mulv("a")
      end, "bad argument #1 to 'mulv' (Vec expected, got string)")
    end)
  end)

  describe("mulv_", function()
    it("should multiply a Vec in-place by another Vec element-wise", function()
      local v1 = Vec(2, 3)
      local v2 = Vec(4, 5)
      v1:mulv_(v2)
      assert.are.same(v1, Vec(8, 15))
    end)
    it("should error if the argument is not a Vec", function()
      local v = Vec(2, 3)
      assert.has_error(function()
        v:mulv_("a")
      end, "bad argument #1 to 'mulv_' (Vec expected, got string)")
    end)
  end)

  describe("div", function()
    it("should divide a Vec by a scalar", function()
      local v = Vec(6, 8)
      local result = v:div(2)
      assert.are.same(result, Vec(3, 4))
    end)
    it("should error if dividing by zero", function()
      assert.has_error(function()
        Vec(6, 8):div(0)
      end, "division by zero")
    end)
    it("should error if the argument is not a number", function()
      assert.has_error(function()
        Vec(6, 8):div("a")
      end, "bad argument #1 to 'div' (finite number expected, got a)")
    end)
  end)

  describe("div_", function()
    it("should divide a Vec in-place by a scalar", function()
      local v = Vec(6, 8)
      v:div_(2)
      assert.are.same(v, Vec(3, 4))
    end)
    it("should error if dividing by zero", function()
      local v = Vec(6, 8)
      assert.has_error(function()
        v:div_(0)
      end, "division by zero")
    end)
    it("should error if the argument is not a number", function()
      local v = Vec(6, 8)
      assert.has_error(function()
        v:div_("a")
      end, "bad argument #1 to 'div_' (finite number expected, got a)")
    end)
  end)

  describe("neg", function()
    it("should negate a Vec", function()
      local v = Vec(1, -2)
      local result = v:neg()
      assert.are.same(result, Vec(-1, 2))
    end)
  end)

  describe("neg_", function()
    it("should negate a Vec in-place", function()
      local v = Vec(1, -2)
      v:neg_()
      assert.are.same(v, Vec(-1, 2))
    end)
  end)
end)
