local Vec = require("src.lovevec")
local assert = require("luassert")

describe("Constructors", function()
  before_each(function()
    Vec.enable_debug(true)
  end)

  after_each(function()
    Vec.enable_debug(false)
  end)

  describe("new", function()
    it("should create a Vec with given x and y", function()
      local v = Vec.new(3, 4)
      assert.are.same(v, Vec(3, 4))
    end)
    it("should create a Vec with default values if no arguments are given", function()
      local v = Vec.new()
      assert.are.same(v, Vec(0, 0))
    end)
    it("errors if x or y is not a finite number", function()
      assert.has_error(function()
        Vec.new("a", 0)
      end, "bad argument #1 to 'new' (finite number expected, got a)")
      assert.has_error(function()
        Vec.new(0, 0 / 0)
      end, "bad argument #2 to 'new' (finite number expected, got nan)")
    end)
  end)

  describe("from_table", function()
    it("should create a Vec from a table in array-style", function()
      local v = Vec.from_table({ 5, 6 })
      assert.are.same(v, Vec(5, 6))
    end)
    it("should create a Vec from a table in key-style", function()
      local v = Vec.from_table({ x = 7, y = 8 })
      assert.are.same(v, Vec(7, 8))
    end)
    it("should create a Vec from a mixed table", function()
      local v = Vec.from_table({ 9, y = 10 })
      assert.are.same(v, Vec(9, 10))
    end)
    it("should error if table is empty", function()
      assert.has_error(function()
        Vec.from_table({})
      end, "bad argument #1 to 'from_table' (finite number expected, got nil)")
    end)
    it("should error if value is not a finite number", function()
      assert.has_error(function()
        Vec.from_table({ 1 / 0, 2 })
      end, "bad argument #1 to 'from_table' (finite number expected, got inf)")
    end)
    it("should error if no table is passed", function()
      assert.has_error(function()
        Vec.from_table("not a table")
      end, "from_table expects a table, got string")
    end)
    it("should error if table has no valid keys", function()
      assert.has_error(function()
        Vec.from_table({ x = 1 })
      end, "bad argument #2 to 'from_table' (finite number expected, got nil)")
    end)
    it("should error if table has invalid keys", function()
      assert.has_error(function()
        Vec.from_table({ x = 1, z = 3 })
      end, "bad argument #2 to 'from_table' (finite number expected, got nil)")
    end)
  end)

  describe("from_polar", function()
    it("should create a Vec from polar coordinates", function()
      local v = Vec.from_polar(5, math.pi / 4)
      assert.are.same(v, Vec(5 * math.cos(math.pi / 4), 5 * math.sin(math.pi / 4)))
    end)
    it("should error if radius or angle is not a finite number", function()
      assert.has_error(function()
        Vec.from_polar("a", 0)
      end, "bad argument #1 to 'from_polar' (finite number expected, got a)")
      assert.has_error(function()
        Vec.from_polar(1, 0 / 0)
      end, "bad argument #2 to 'from_polar' (finite number expected, got nan)")
    end)
  end)

  describe("from_polar_deg", function()
    it("should create a Vec from polar coordinates in degrees", function()
      local v = Vec.from_polar_deg(5, 45)
      assert.are.same(v, Vec(5 * math.cos(math.rad(45)), 5 * math.sin(math.rad(45))))
    end)
    it("should error if radius or angle is not a finite number", function()
      assert.has_error(function()
        Vec.from_polar_deg("a", 0)
      end, "bad argument #1 to 'from_polar_deg' (finite number expected, got a)")
      assert.has_error(function()
        Vec.from_polar_deg(1, 0 / 0)
      end, "bad argument #2 to 'from_polar_deg' (finite number expected, got nan)")
    end)
  end)

  describe("random", function()
    local eps = 1e-12 -- tighter tolerance for random values
    it("should create a Vec with random values in the unit circle", function()
      local v = Vec.random()
      assert.is_true(math.abs(v:length() - 1) < eps)
      assert.is_true(v.x >= -1 and v.x <= 1)
      assert.is_true(v.y >= -1 and v.y <= 1)
    end)
    it("should create a Vec with random values within a given radius", function()
      local v = Vec.random(2)
      assert.is_true(math.abs(v:length() - 2) < eps)
      assert.is_true(v.x >= -2 and v.x <= 2)
      assert.is_true(v.y >= -2 and v.y <= 2)
    end)
    it("should create a zero Vec if radius is 0", function()
      local v = Vec.random(0)
      assert.are.same(v, Vec(0, 0))
    end)
    it("should error if radius is not a finite number", function()
      assert.has_error(function()
        Vec.random("a")
      end, "bad argument #1 to 'random' (finite number expected, got a)")
    end)
    it("should error if radius is a negative number", function()
      assert.has_error(function()
        Vec.random(-1)
      end, "radius must be non-negative")
    end)
  end)

  describe("acc", function()
    it("should accumulate multiple Vecs into one", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(3, 4)
      local v3 = Vec(5, 6)
      local v = Vec.acc(v1, v2, v3)
      assert.are.same(v, Vec(9, 12))
    end)
    it("should handle nil arguments gracefully", function()
      local v1 = Vec(1, 2)
      local v2 = nil
      local v3 = Vec(5, 6)
      local v = Vec.acc(v1, v2, v3)
      assert.are.same(v, Vec(6, 8))
    end)
    it("should return a zero Vec if no arguments are given", function()
      local v = Vec.acc()
      assert.are.same(v, Vec(0, 0))
    end)
    it("should return a zero Vec if all arguments are nil", function()
      local v = Vec.acc(nil, nil)
      assert.are.same(v, Vec(0, 0))
    end)
    it("should error if any argument is not a Vec", function()
      assert.has_error(function()
        Vec.acc(Vec(1, 2), "not a Vec")
      end, "bad argument #2 to 'acc' (Vec expected, got string)")
    end)
  end)
end)
