local Vec = require("src.lovevec")
local assert = require("luassert")

describe("Core", function()
  before_each(function()
    Vec.enable_debug(true)
  end)

  after_each(function()
    Vec.enable_debug(false)
  end)

  describe("clone", function()
    it("should clone a Vec", function()
      local v = Vec(1, 2)
      local clone = v:clone()
      v.x = 3

      assert.are.same(v, Vec(3, 2))
      assert.are.same(clone, Vec(1, 2))
      assert.are_not.same(v, clone)
    end)
  end)

  describe("unpack", function()
    it("should unpack a Vec into its x and y components", function()
      local v = Vec(3, 4)
      local x, y = v:unpack()
      assert.are.equal(x, 3)
      assert.are.equal(y, 4)
    end)
  end)

  describe("to_table", function()
    it("should convert a Vec to a table with x and y components", function()
      local v = Vec(5, 6)
      local t = v:to_table()
      assert.are.same(t, { 5, 6 })
    end)
  end)

  describe("length_manhattan", function()
    it("should return the Manhattan length of a Vec", function()
      local v = Vec(3, 4)
      local len = v:length_manhattan()
      assert.are.equal(len, 7)
    end)
  end)

  describe("length_squared", function()
    it("should return the squared length of a Vec", function()
      local v = Vec(3, 4)
      local len_sq = v:length_squared()
      assert.are.equal(len_sq, 25)
    end)
  end)

  describe("length", function()
    it("should return the length of a Vec", function()
      local v = Vec(3, 4)
      local len = v:length()
      assert.are.equal(len, 5)
    end)
  end)

  describe("dot", function()
    it("should return the dot product of two Vecs", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(3, 4)
      local dot_product = v1:dot(v2)
      assert.are.equal(dot_product, 11)
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):dot("a")
      end, "bad argument #1 to 'dot' (Vec expected, got string)")
    end)
  end)

  describe("cross", function()
    it("should return the cross product of two Vecs", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(3, 4)
      local cross_product = v1:cross(v2)
      assert.are.equal(cross_product, -2)
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):cross("a")
      end, "bad argument #1 to 'cross' (Vec expected, got string)")
    end)
  end)

  describe("normalize", function()
    it("should normalize a Vec to unit length", function()
      local v = Vec(3, 4)
      local normalized = v:normalize()
      assert.are.equal(normalized:length(), 1)
      assert.are.same(normalized, Vec(0.6, 0.8))
    end)
    it("should return a zero Vec if the length is zero", function()
      local v = Vec(0, 0)
      local normalized = v:normalize()
      assert.are.same(normalized, Vec(0, 0))
    end)
  end)

  describe("normalize_", function()
    it("should normalize a Vec in-place to unit length", function()
      local v = Vec(3, 4)
      v:normalize_()
      assert.are.equal(v:length(), 1)
      assert.are.same(v, Vec(0.6, 0.8))
    end)
    it("should return a zero Vec if the length is zero", function()
      local v = Vec(0, 0)
      v:normalize_()
      assert.are.same(v, Vec(0, 0))
    end)
  end)

  describe("perp", function()
    it("should return a Vec perpendicular to the original", function()
      local v = Vec(3, 4)
      local perp = v:perp()
      assert.are.same(perp, Vec(-4, 3))
    end)
  end)

  describe("perp_", function()
    it("should set the Vec to its perpendicular in-place", function()
      local v = Vec(3, 4)
      v:perp_()
      assert.are.same(v, Vec(-4, 3))
    end)
  end)

  describe("project", function()
    it("should project a Vec onto another Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(1, 0)
      local projection = v1:project(v2)
      assert.are.same(projection, Vec(3, 0))
    end)
    it("should return a zero Vec if projecting onto a zero Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(0, 0)
      local projection = v1:project(v2)
      assert.are.same(projection, Vec(0, 0))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(3, 4):project("a")
      end, "bad argument #1 to 'project' (Vec expected, got string)")
    end)
  end)

  describe("project_", function()
    it("should project a Vec onto another Vec in-place", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(1, 0)
      v1:project_(v2)
      assert.are.same(v1, Vec(3, 0))
    end)
    it("should return a zero Vec if projecting onto a zero Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(0, 0)
      v1:project_(v2)
      assert.are.same(v1, Vec(0, 0))
    end)
    it("should error if the argument is not a Vec", function()
      local v = Vec(3, 4)
      assert.has_error(function()
        v:project_("a")
      end, "bad argument #1 to 'project_' (Vec expected, got string)")
    end)
  end)

  describe("reject", function()
    it("should reject a Vec from another Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(1, 0)
      local rejection = v1:reject(v2)
      assert.are.same(rejection, Vec(0, 4))
    end)
    it("should return a zero Vec if rejecting from a zero Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(3, 4)
      local rejection = v1:reject(v2)
      assert.are.same(rejection, Vec(0, 0))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(3, 4):reject("a")
      end, "bad argument #1 to 'reject' (Vec expected, got string)")
    end)
  end)

  describe("reject_", function()
    it("should reject a Vec from another Vec in-place", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(1, 0)
      v1:reject_(v2)
      assert.are.same(v1, Vec(0, 4))
    end)
    it("should return a zero Vec if rejecting from a zero Vec", function()
      local v1 = Vec(3, 4)
      local v2 = Vec(3, 4)
      v1:reject_(v2)
      assert.are.same(v1, Vec(0, 0))
    end)
    it("should error if the argument is not a Vec", function()
      local v = Vec(3, 4)
      assert.has_error(function()
        v:reject_("a")
      end, "bad argument #1 to 'reject_' (Vec expected, got string)")
    end)
  end)

  describe("clamp", function()
    it("should clamp a Vec to a specified range", function()
      local v = Vec(5, -3)
      local clamped = v:clamp(Vec(-1, -1), Vec(2, 2))
      assert.are.same(clamped, Vec(2, -1))
    end)
    it("should error if the min or max is not a Vec", function()
      local v = Vec(5, -3)
      assert.has_error(function()
        v:clamp("not a vec", Vec(2, 2))
      end, "bad argument #1 to 'clamp' (Vec expected, got string)")
      assert.has_error(function()
        v:clamp(Vec(-1, -1), "not a vec")
      end, "bad argument #2 to 'clamp' (Vec expected, got string)")
    end)
    it("should error if the min Vec is greater than the max Vec", function()
      local v = Vec(5, -3)
      assert.has_error(function()
        v:clamp(Vec(2, 2), Vec(-1, -1))
      end, "min cannot be greater than max")
    end)
  end)

  describe("clamp_", function()
    it("should clamp a Vec in-place to a specified range", function()
      local v = Vec(5, -3)
      v:clamp_(Vec(-1, -1), Vec(2, 2))
      assert.are.same(v, Vec(2, -1))
    end)
    it("should error if the min or max is not a Vec", function()
      local v = Vec(5, -3)
      assert.has_error(function()
        v:clamp_("not a vec", Vec(2, 2))
      end, "bad argument #1 to 'clamp_' (Vec expected, got string)")
      assert.has_error(function()
        v:clamp_(Vec(-1, -1), "not a vec")
      end, "bad argument #2 to 'clamp_' (Vec expected, got string)")
    end)
    it("should error if the min Vec is greater than the max Vec", function()
      local v = Vec(5, -3)
      assert.has_error(function()
        v:clamp_(Vec(2, 2), Vec(-1, -1))
      end, "min cannot be greater than max")
    end)
  end)

  describe("limit", function()
    it("should limit a Vec to a maximum length", function()
      local v = Vec(2, 0)
      local limited = v:limit(1)
      assert.are.same(limited, Vec(1, 0))
      assert.are.equal(limited:length(), 1)
    end)
    it("should return the original Vec if already within the limit", function()
      local v = Vec(2, 0)
      local limited = v:limit(3)
      assert.are.same(limited, v)
      assert.are.equal(limited:length(), 2)
    end)
    it("should return a zero Vec if the limit is zero", function()
      local v = Vec(3, 4)
      local limited = v:limit(0)
      assert.are.same(limited, Vec(0, 0))
    end)
    it("should error if the limit is not a finite number", function()
      assert.has_error(function()
        Vec(3, 4):limit("a")
      end, "bad argument #1 to 'limit' (finite number expected, got a)")
    end)
  end)

  describe("limit_", function()
    it("should limit a Vec in-place to a maximum length", function()
      local v = Vec(2, 0)
      v:limit_(1)
      assert.are.same(v, Vec(1, 0))
      assert.are.equal(v:length(), 1)
    end)
    it("should return the original Vec if already within the limit", function()
      local v = Vec(2, 0)
      v:limit_(3)
      assert.are.same(v, Vec(2, 0))
    end)
    it("should return a zero Vec if the limit is zero", function()
      local v = Vec(3, 4)
      v:limit_(0)
      assert.are.same(v, Vec(0, 0))
    end)
    it("should error if the limit is not a finite number", function()
      assert.has_error(function()
        Vec(3, 4):limit_("a")
      end, "bad argument #1 to 'limit_' (finite number expected, got a)")
    end)
  end)

  describe("lerp", function()
    it("should linearly interpolate between two Vecs", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      local t = 0.5
      local result = v1:lerp(v2, t)
      assert.are.same(result, Vec(5, 5))
    end)
    it("should return the first Vec if t is 0", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      local result = v1:lerp(v2, 0)
      assert.are.same(result, v1)
    end)
    it("should return the second Vec if t is 1", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      local result = v1:lerp(v2, 1)
      assert.are.same(result, v2)
    end)
    it("should error if the first argument is not a Vec", function()
      assert.has_error(function()
        Vec(0, 0):lerp({}, 0.5)
      end, "bad argument #1 to 'lerp' (Vec expected, got table)")
    end)
    it("should error if t is not a finite number", function()
      assert.has_error(function()
        Vec(0, 0):lerp(Vec(10, 10), "a")
      end, "bad argument #2 to 'lerp' (finite number expected, got a)")
    end)
  end)

  describe("lerp_", function()
    it("should linearly interpolate a Vec in-place", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      local t = 0.5
      v1:lerp_(v2, t)
      assert.are.same(v1, Vec(5, 5))
    end)
    it("should return the first Vec if t is 0", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      v1:lerp_(v2, 0)
      assert.are.same(v1, Vec(0, 0))
    end)
    it("should return the second Vec if t is 1", function()
      local v1 = Vec(0, 0)
      local v2 = Vec(10, 10)
      v1:lerp_(v2, 1)
      assert.are.same(v1, Vec(10, 10))
    end)
    it("should error if the first argument is not a Vec", function()
      assert.has_error(function()
        Vec(0, 0):lerp_({}, 0.5)
      end, "bad argument #1 to 'lerp_' (Vec expected, got table)")
    end)
    it("should error if t is not a finite number", function()
      assert.has_error(function()
        Vec(0, 0):lerp_(Vec(10, 10), "a")
      end, "bad argument #2 to 'lerp_' (finite number expected, got a)")
    end)
  end)

  describe("round", function()
    it("should round a Vec to the nearest integers", function()
      local v = Vec(3.6, 4.2)
      local rounded = v:round()
      assert.are.same(rounded, Vec(4, 4))
    end)
  end)

  describe("round_", function()
    it("should round a Vec in-place to the nearest integers", function()
      local v = Vec(3.6, 4.2)
      v:round_()
      assert.are.same(v, Vec(4, 4))
    end)
  end)

  describe("floor", function()
    it("should floor a Vec to the nearest lower integers", function()
      local v = Vec(3.6, 4.2)
      local floored = v:floor()
      assert.are.same(floored, Vec(3, 4))
    end)
  end)

  describe("floor_", function()
    it("should floor a Vec in-place to the nearest lower integers", function()
      local v = Vec(3.6, 4.2)
      v:floor_()
      assert.are.same(v, Vec(3, 4))
    end)
  end)

  describe("ceil", function()
    it("should ceil a Vec to the nearest upper integers", function()
      local v = Vec(3.6, 4.2)
      local ceiled = v:ceil()
      assert.are.same(ceiled, Vec(4, 5))
    end)
  end)

  describe("ceil_", function()
    it("should ceil a Vec in-place to the nearest upper integers", function()
      local v = Vec(3.6, 4.2)
      v:ceil_()
      assert.are.same(v, Vec(4, 5))
    end)
  end)

  describe("swap", function()
    it("should swap the x and y components of a Vec", function()
      local v = Vec(3, 4)
      local swapped = v:swap()
      assert.are.same(swapped, Vec(4, 3))
    end)
  end)

  describe("swap_", function()
    it("should swap the x and y components of a Vec in-place", function()
      local v = Vec(3, 4)
      v:swap_()
      assert.are.same(v, Vec(4, 3))
    end)
  end)

  describe("rotate", function()
    -- it("should rotate a Vec by a given angle in radians", function()
    --   local v = Vec(1, 0)
    --   local angle = math.pi / 2 -- 90 degrees
    --   local rotated = v:rotate(angle)
    --   assert.are.same(rotated, Vec(0, 1))
    --   -- FIXME: x = 6.1232339957367660359e-17
    -- end)
    it("should rotate a Vec around a pivot by a given angle in radians", function()
      local v = Vec(2, 1)
      local angle = math.pi / 2 -- 90 degrees
      local pivot = Vec(1, 1)
      local rotated = v:rotate(angle, pivot)
      assert.are.same(rotated, Vec(1, 0))
    end)
    it("should error if the angle is not a finite number", function()
      assert.has_error(function()
        Vec(1, 0):rotate("a")
      end, "bad argument #1 to 'rotate' (finite number expected, got a)")
    end)
    it("should error if pivot is not a Vec", function()
      assert.has_error(function()
        Vec(1, 0):rotate(math.pi / 2, "not a vec")
      end, "bad argument #2 to 'rotate' (Vec expected, got string)")
    end)
  end)

  describe("rotate_", function()
    -- it("should rotate a Vec in-place by a given angle in radians", function()
    --   local v = Vec(1, 0)
    --   local angle = math.pi / 2 -- 90 degrees
    --   v:rotate_(angle)
    --   assert.are.same(v, Vec(0, -1))
    --   -- FIXME: x = 6.1232339957367660359e-17
    -- end)
    it("should rotate a Vec around a pivot by a given angle in radians in-place", function()
      local v = Vec(2, 1)
      local angle = math.pi / 2 -- 90 degrees
      local pivot = Vec(1, 1)
      v:rotate_(angle, pivot)
      assert.are.same(v, Vec(1, 0))
    end)
    it("should error if the angle is not a finite number", function()
      assert.has_error(function()
        Vec(1, 0):rotate_("a")
      end, "bad argument #1 to 'rotate_' (finite number expected, got a)")
    end)
    it("should error if pivot is not a Vec", function()
      assert.has_error(function()
        Vec(1, 0):rotate_(math.pi / 2, "not a vec")
      end, "bad argument #2 to 'rotate_' (Vec expected, got string)")
    end)
  end)

  describe("reflect", function()
    it("should reflect a Vec across a line defined by another Vec", function()
      local v = Vec(1, 1)
      local line = Vec(0, 1) -- Vertical line
      local reflected = v:reflect(line)
      assert.are.same(reflected, Vec(1, -1))
    end)
    it("should return the original Vec if reflecting across a zero Vec", function()
      local v = Vec(1, 1)
      local line = Vec(0, 0)
      local reflected = v:reflect(line)
      assert.are.same(reflected, v)
    end)
    it("should error if the line is not a Vec", function()
      assert.has_error(function()
        Vec(1, 1):reflect("not a vec")
      end, "bad argument #1 to 'reflect' (Vec expected, got string)")
    end)
  end)

  describe("reflect_", function()
    it("should reflect a Vec across a line defined by another Vec in-place", function()
      local v = Vec(1, 1)
      local line = Vec(0, 1) -- Vertical line
      v:reflect_(line)
      assert.are.same(v, Vec(1, -1))
    end)
    it("should return the original Vec if reflecting across a zero Vec", function()
      local v = Vec(1, 1)
      local line = Vec(0, 0)
      v:reflect_(line)
      assert.are.same(v, Vec(1, 1))
    end)
    it("should error if the line is not a Vec", function()
      local v = Vec(1, 1)
      assert.has_error(function()
        v:reflect_("not a vec")
      end, "bad argument #1 to 'reflect_' (Vec expected, got string)")
    end)
  end)

  describe("distance", function()
    it("should return the distance between two Vecs", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(4, 6)
      local dist = v1:distance(v2)
      assert.are.equal(dist, 5)
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):distance("a")
      end, "bad argument #1 to 'distance' (Vec expected, got string)")
    end)
  end)

  describe("distance_manhattan", function()
    it("should return the Manhattan distance between two Vecs", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(4, 6)
      local dist = v1:distance_manhattan(v2)
      assert.are.equal(dist, 7)
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):distance_manhattan("a")
      end, "bad argument #1 to 'distance_manhattan' (Vec expected, got string)")
    end)
  end)

  describe("angle", function()
    it("should return the angle in radians between two Vecs", function()
      local v1 = Vec(1, 0)
      local v2 = Vec(0, 1)
      local angle = v1:angle(v2)
      assert.are.equal(angle, math.pi / 2) -- 90 degrees
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 0):angle("a")
      end, "bad argument #1 to 'angle' (Vec expected, got string)")
    end)
  end)

  describe("angle_of", function()
    it("should return the angle in radians of a Vec", function()
      local v = Vec(1, 1)
      local angle = v:angle_of()
      assert.are.equal(angle, math.pi / 4) -- 45 degrees
    end)
  end)

  describe("angle_to", function()
    it("should return the angle in radians from this Vec to another Vec", function()
      local v1 = Vec(1, 0)
      local v2 = Vec(0, 1)
      local angle = v1:angle_to(v2)
      assert.are.equal(angle, math.pi / 2) -- 90 degrees
    end)
    it("should return the angle in radians from this Vec to itself", function()
      local v = Vec(1, 0)
      local angle = v:angle_to(v)
      assert.are.equal(angle, 0) -- Angle to itself should be zero
    end)
    it("should return zero angle to a zero Vec", function()
      local v1 = Vec(1, 0)
      local v2 = Vec(0, 0)
      local angle = v1:angle_to(v2)
      assert.are.equal(angle, 0) -- Angle to zero Vec should be zero
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 0):angle_to("a")
      end, "bad argument #1 to 'angle_to' (Vec expected, got string)")
    end)
  end)

  describe("eq", function()
    it("should compare two Vecs for equality", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(1, 2)
      local v3 = Vec(2, 1)
      assert.is_true(v1:eq(v2))
      assert.is_false(v1:eq(v3))
    end)
    it("should apply a tolerance when comparing", function()
      local eps = 1e-12
      local v1 = Vec(1, 2)
      local v2 = Vec(1 + eps / 2, 2 - eps / 2)
      local v3 = Vec(1 + eps, 2 - eps)

      Vec._EPS = eps
      assert.is_true(v1:eq(v2))
      assert.is_false(v1:eq(v3))
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):eq("a")
      end, "bad argument #1 to 'eq' (Vec expected, got string)")
    end)
    it("should error if the tolerance is not a finite number", function()
      assert.has_error(function()
        Vec(1, 2):eq(Vec(1, 2), "a")
      end, "bad argument #2 to 'eq' (finite number expected, got a)")
    end)
  end)

  describe("strict_eq", function()
    it("should compare two Vecs for strict equality", function()
      local v1 = Vec(1, 2)
      local v2 = Vec(1, 2)
      local v3 = Vec(2, 1)
      assert.is_true(v1:strict_eq(v2))
      assert.is_false(v1:strict_eq(v3))
    end)
    it("should not apply a tolerance when comparing", function()
      local eps = 1e-12
      local v1 = Vec(1, 2)
      local v2 = Vec(1 + eps / 2, 2 - eps / 2)
      local v3 = Vec(1 + eps, 2 - eps)
      assert.is_false(v1:strict_eq(v2)) -- Should be false due to strict equality
      assert.is_false(v1:strict_eq(v3)) -- Should be false due to strict equality
    end)
    it("should error if the argument is not a Vec", function()
      assert.has_error(function()
        Vec(1, 2):strict_eq("a")
      end, "bad argument #1 to 'strict_eq' (Vec expected, got string)")
    end)
  end)
end)
